tag_map = {
    "others": {'Lento',
               'Não encontrei meu problema',
               'Outro Tipo de produto/Serviço',
               'Outro problema',
               'Outros'},
    'products': {'Acessórios de Vestuário',
                 'Acessórios para Bebê',
                 'Acessórios para Carros',
                 'Alto falantes',
                 'Aparadores',
                 'Aparelho de jantar',
                 'Aparelhos de musculação',
                 'Aparelhos de som',
                 'Ar condicionado',
                 'Armários de cozinha',
                 'Aromatizantes e Difusores',
                 'Artigos Religiosos',
                 'Artigos para bebê',
                 'Aspiradores e vassouras',
                 'Balanças',
                 'Bancos e banquetas',
                 'Berço desmontável',
                 'Bikes',
                 'Bolsas',
                 'Bolsas e Malas',
                 'Bonecos e Bonecas',
                 'Brinquedos e jogos',
                 'Brinquedos eletrônicos',
                 'Brinquedos para bebês',
                 'Cabeceira',
                 'Cadeiras',
                 'Cafeteiras e Chaleiras',
                 'Caixas de som e fone de ouvido',
                 'Cama, Mesa e Banho',
                 'Camas e camas-box',
                 'Celular',
                 'Celulares e Smartphones',
                 'Chapinhas (Pranchas)',
                 'Churrasqueira',
                 'Chuveiro elétrico',
                 'Chuveiros e Aquecedores',
                 'Climatizador de ar',
                 'Clubes de Compras e Vantagens',
                 'Coifa e depurador',
                 'Colchões',
                 'Colchões e acessórios',
                 'Componentes, peças e acessórios',
                 'Computadores all in one',
                 'Console (Videogame)',
                 'Controle remoto',
                 'Controles e Joysticks',
                 'Conversor digital',
                 'Cooktop',
                 'Cortina',
                 'Cristaleiras',
                 'Câmera',
                 'Decoração',
                 'Eletrodomésticos',
                 'Eletroeletrônicos',
                 'Eletroportáteis',
                 'Equipamentos de Beleza e Estética',
                 'Equipamentos de academia',
                 'Equipamentos de rede-Wireless',
                 'Escovas - Modeladores - Babyliss',
                 'Farmácias',
                 'Ferro de passar',
                 'Fios e cabos',
                 'Fogão-Forno',
                 'Fone de ouvido',
                 'Frigobar',
                 'Fritadeira elétrica',
                 'Fôrmas e assadeiras',
                 'Games e Jogos',
                 'Gel',
                 'Geladeira-Refrigerador',
                 'Guarda-Roupas',
                 'Higiene e Limpeza Pessoal',
                 'Iluminação e Elétrica',
                 'Impressoras',
                 'Informática',
                 'Jogo de cama',
                 'Jogos',
                 'Lava louças',
                 'Lavadora de roupas e Tanquinho',
                 'Leitores de Ebooks',
                 'Lençol',
                 'Liquidificadores',
                 'Livros',
                 'Lixeiras',
                 'Louças',
                 'Louças e Metais',
                 'MP3 Player',
                 'Mesa de jantar',
                 'Mesas e Cadeiras',
                 'Micro-ondas',
                 'Milhas',
                 'Mixers e Processadores de alimentos',
                 'Mochilas',
                 'Monitores',
                 'Máquinas de cortar o cabelo',
                 'Móveis',
                 'Móveis Infantis',
                 'Móveis Modulados',
                 'Móveis Planejados',
                 'Móveis em Geral',
                 'Móveis para Escritório',
                 'Móveis para Jardim e Piscina',
                 'Notebooks',
                 'Organizadores de cozinha',
                 'Painéis para TV',
                 'Panela',
                 'Panela elétrica',
                 'Perfumarias',
                 'Perfume',
                 'Pisos e Revestimentos Vinílicos',
                 'Plafon',
                 'Players de DVD-Blue Ray',
                 'Poltronas',
                 'Pontos',
                 'Porta Livros',
                 'Portas',
                 'Portas e Janelas',
                 'Potes',
                 'Prateleiras e cantoneiras',
                 'Rack e bancadas',
                 'Relógios',
                 'Sabonete líquido',
                 'Secador de cabelo',
                 'Secadora de roupa e centrífuga',
                 'Smartphone',
                 'Sofás e Estofados',
                 'TV',
                 'Tablets',
                 'Talheres',
                 'Tapetes',
                 'Tapetes e Carpetes',
                 'Teclados',
                 'Telefones fixos (aparelhos)',
                 'Toalhas',
                 'Travesseiros',
                 'Utilidades domésticas',
                 'Ventiladores e Circuladores de ar',
                 'Vidros',
                 'Vidros e Espelhos'},
    "product_issues": {
        'Amassado',
        'Braço quebrado',
        'Braço solto',
        'Cadeira bamba',
        'Atraso na entrega',
        'Atraso na entrega do produto',
        'Colchão irregular',
        'Danos ao imóvel',
        'Deformado',
        'Desconfortável',
        'Descosturado',
        'Desgaste prematuro',
        'Desligando sozinha',
        'Desligando sozinho',
        'Dificuldade para abrir-fechar a porta',
        'Encosto com problema',
        'Encosto quebrado',
        'Entrega',
        'Esquentando',
        'Estofamento manchado',
        'Estofamento rasgado',
        'Estrado quebrado',
        'Falta de peças',
        'Falta de peças para reparo',
        'Fazendo muito barulho',
        'Gavetas não abrem-fecham',
        'Incompatibilidade',
        'Inferior ao vendido',
        'Instalação-Reparo não concluídos',
        'Liga e desliga sozinho',
        'Mesa bamba',
        'Mesa quebrada',
        'Mesa riscada',
        'Molas quebradas',
        'Montagem',
        'Má qualidade do produto',
        'Não acende',
        'Não aguenta peso',
        'Não atende',
        'Não carrega',
        'Não conecta à intenet',
        'Não gela',
        'Não liga',
        'Não recebi',
        'Perdendo fio',
        'Pernas quebradas',
        'Peças erradas',
        'Peças faltando',
        'Peças quebradas',
        'Problema nas bocas do fogão',
        'Problemas com a tela',
        'Problemas de coluna causados pelo colchão',
        'Problemas de sinal',
        'Produto com defeito',
        'Produto com peças faltando',
        'Produto danificado',
        'Produto errado',
        'Produto indisponível',
        'Produto não parece original',
        'Produto não recebido',
        'Produto não reparado',
        'Produto quebrou com pouco tempo de uso',
        'Produto rasgado',
        'Produto usado',
        'Produtos divergentes',
        'Projeto divergente',
        'Pé quebrado',
        'Qualidade do Produto',
        'Qualidade do produto',
        'Tampa trincada-quebrada',
        'Tecido de baixa qualidade',
        'Tela manchada',
        'Tela quebrada',
        'Vazando água',
        'Vidro quebrado',
    },
    "business_issues": {
        'Aplicativos',
        'Atendimento na Loja',
        'Atraso no reembolso por cancelamento',
        'Cartão de crédito',
        'Cartões de Crédito',
        'Canais de Atendimento',
        'Comportamento do profissional',
        'Demora no atendimento',
        'Demora no reparo',
        'Desacordo Comercial',
        'Divergência de valores',
        'Equipe de Atendimento',
        'Estado de conservação da loja',
        'Estorno do valor pago',
        'Fila',
        'Forma de pagamento indisponível',
        'Funcionários despreparados',
        'Maquiagem de preço',
        'Marketplace',
        'Mau Atendimento',
        'Mau atendimento no SAC',
        'Não consigo agendar',
        'Não consigo fazer operação por telefone',
        'Problema com garantia estendida',
        'Problemas com as ligações',
        'Problemas com lojas de móveis',
        'Problemas com o Atendimento',
        'Problemas com o Site',
        'Problemas na Loja',
        'Problemas na finalização da compra',
        'Problemas para utilizar aplicativos',
        'Troca-Devolução de produto',
        'Promoção',
        'Propaganda Enganosa',
        'Propaganda enganosa',
        'Pré venda e Projeto',
        'Qualidade do serviço prestado',
        'Serviço não incluso na garantia',
        'Site fora do ar-Lento',
        'Sites e portais',
        'Valor de frete',
        'Assistência técnica e Garantia',
        'Assistência técnica', 'Assistência técnica indisponível',
    }
}
