tag_map = {
    "others": {
        'Lento',
        'Não encontrei meu problema',
        'Outro Tipo de produto/Serviço',
        'Outro problema',
        'Outros'
    },
    'products': {
        'Home Appliances': {
            'Alto falantes',
            'Aparelhos de som',
            'Ar condicionado',
            'Caixas de som e fone de ouvido',
            'Chuveiro elétrico',
            'Chuveiros e Aquecedores',
            'Climatizador de ar',
            'Coifa e depurador',
            'Conversor digital',
            'Cooktop',
            'Eletrodomésticos',
            'Ferro de passar',
            'Fogão-Forno',
            'Frigobar',
            'Fritadeira elétrica',
            'Geladeira-Refrigerador',
            'Impressoras',
            'Lava louças',
            'Lavadora de roupas e Tanquinho',
            'Liquidificadores',
            'Micro-ondas',
            'Ventiladores e Circuladores de ar',
            'Panela elétrica',
            'Players de DVD-Blue Ray',
            'TV',
            'Telefones fixos (aparelhos)',
            'Mixers e Processadores de alimentos',
            'Secadora de roupa e centrífuga',
            'Aspiradores e vassouras',
            'Balanças',
            'Cafeteiras e Chaleiras',
        },
        'Eletronics': {
            'Celular',
            'Celulares e Smartphones',
            'Computadores all in one',
            'Console (Videogame)',
            'Eletroeletrônicos',
            'Eletroportáteis',
            'Equipamentos de rede-Wireless',
            'Leitores de Ebooks',
            'MP3 Player',
            'Monitores',
            'Notebooks',
            'Smartphone',
            'Tablets',
            'Câmera'
        },
        'Furniture': {
            'Aparadores',
            'Aparelho de jantar',
            'Armários de cozinha',
            'Bancos e banquetas',
            'Berço desmontável',
            'Cabeceira',
            'Cadeiras',
            'Guarda-Roupas',
            'Mesa de jantar',
            'Mesas e Cadeiras',
            'Móveis',
            'Móveis Infantis',
            'Móveis Modulados',
            'Móveis Planejados',
            'Móveis em Geral',
            'Móveis para Escritório',
            'Móveis para Jardim e Piscina',
            'Painéis para TV',
            'Poltronas',
            'Sofás e Estofados',
            'Tapetes',
            'Tapetes e Carpetes',
            'Prateleiras e cantoneiras',
            'Rack e bancadas',
            'Camas e camas-box',
            'Churrasqueira',
            'Lixeiras'
        },
        'Accessories': {
            'Acessórios de Vestuário',
            'Acessórios para Bebê',
            'Acessórios para Carros',
            'Componentes, peças e acessórios',
            'Controle remoto',
            'Controles e Joysticks',
            'Fios e cabos',
            'Fone de ouvido',
            'Cama, Mesa e Banho',
            'Talheres',
            'Toalhas',
            'Travesseiros',
            'Aromatizantes e Difusores',
            'Fôrmas e assadeiras',
            'Colchões',
            'Colchões e acessórios',
            'Jogo de cama',
            'Lençol',
            'Louças',
            'Louças e Metais',
            'Organizadores de cozinha',
            'Panela',
            'Potes',
            'Utilidades domésticas',
            'Teclados',
            'Porta Livros'
        },
        'Decoration': {
            'Cortina',
            'Decoração',
            'Cristaleiras',
            'Iluminação e Elétrica',
            'Pisos e Revestimentos Vinílicos',
            'Plafon',
            'Portas',
            'Portas e Janelas',
            'Vidros',
            'Vidros e Espelhos',
            'Relógios'
        },
        'Others': {
            'Aparelhos de musculação',
            'Artigos Religiosos',
            'Artigos para bebê',
            'Bikes',
            'Bolsas',
            'Bolsas e Malas',
            'Bonecos e Bonecas',
            'Brinquedos e jogos',
            'Brinquedos eletrônicos',
            'Brinquedos para bebês',
            'Equipamentos de Beleza e Estética',
            'Equipamentos de academia',
            'Escovas - Modeladores - Babyliss',
            'Farmácias',
            'Chapinhas (Pranchas)',
            'Games e Jogos',
            'Gel',
            'Higiene e Limpeza Pessoal',
            'Informática',
            'Jogos',
            'Livros',
            'Mochilas',
            'Máquinas de cortar o cabelo',
            'Perfumarias',
            'Perfume',
            'Sabonete líquido',
            'Secador de cabelo'
        }
    },
    "product_issues": {
        'Quality': {
            'Desconfortável',
            'Desgaste prematuro',
            'Inferior ao vendido',
            'Qualidade do Produto',
            'Qualidade do produto',
            'Tecido de baixa qualidade',
            'Má qualidade do produto',
            'Produto não parece original',
            'Problemas de coluna causados pelo colchão',
            'Produto com defeito',
            'Produto usado',
            'Produto quebrou com pouco tempo de uso',
            'Incompatibilidade'
        },
        'Damaged': {
            'Amassado',
            'Braço quebrado',
            'Braço solto',
            'Deformado',
            'Descosturado',
            'Mesa riscada',
            'Colchão irregular',
            'Dificuldade para abrir-fechar a porta',
            'Encosto com problema',
            'Encosto quebrado',
            'Estofamento manchado',
            'Estofamento rasgado',
            'Estrado quebrado',
            'Fazendo muito barulho',
            'Gavetas não abrem-fecham',
            'Mesa bamba',
            'Mesa quebrada',
            'Cadeira bamba',
            'Molas quebradas',
            'Não aguenta peso',
            'Perdendo fio',
            'Pernas quebradas',
            'Peças quebradas',
            'Problema nas bocas do fogão',
            'Produto danificado',
            'Produto rasgado',
            'Pé quebrado',
            'Tampa trincada-quebrada',
            'Vazando água',
            'Vidro quebrado'
        },
        'Electrical problems': {
            'Desligando sozinha',
            'Desligando sozinho',
            'Esquentando',
            'Liga e desliga sozinho',
            'Não acende',
            'Não atende',
            'Não carrega',
            'Não conecta à intenet',
            'Não gela',
            'Não liga',
            'Tela manchada',
            'Tela quebrada'
            'Problemas com a tela',
            'Problemas de sinal'
        },
        'Missing pieces': {
            'Peças erradas',
            'Peças faltando',
            'Falta de peças',
            'Falta de peças para reparo'
            'Produto com peças faltando'
        }
    },
    "business_issues": {
        'Payment': {
            'Atraso no reembolso por cancelamento',
            'Cartão de crédito',
            'Cartões de Crédito',
            'Divergência de valores',
            'Estorno do valor pago',
            'Forma de pagamento indisponível',
            'Maquiagem de preço',
            'Problemas na finalização da compra',
            'Valor de frete'
        },
        'Maintenance': {
            'Demora no reparo',
            'Assistência técnica e Garantia',
            'Assistência técnica',
            'Assistência técnica indisponível',
            'Problema com garantia estendida',
            'Serviço não incluso na garantia',
            'Produto não reparado'
        },
        'Customer Services': {
            'Atendimento na Loja',
            'Comportamento do profissional',
            'Demora no atendimento',
            'Funcionários despreparados',
            'Equipe de Atendimento',
            'Mau Atendimento',
            'Mau atendimento no SAC',
            'Problemas com as ligações',
            'Problemas com lojas de móveis',
            'Problemas com o Atendimento',
            'Não consigo agendar',
            'Não consigo fazer operação por telefone',
            'Problemas na Loja'
            'Troca-Devolução de produto',
            'Promoção',
            'Propaganda Enganosa',
            'Propaganda enganosa',
            'Qualidade do serviço prestado',
            'Desacordo Comercial',
            'Pré venda e Projeto',
            'Estado de conservação da loja',
            'Fila',
            'Clubes de Compras e Vantagens',
            'Milhas',
            'Pontos',
            'Produto indisponível'
        },
        'Delivery': {
            'Atraso na entrega',
            'Atraso na entrega do produto',
            'Danos ao imóvel',
            'Entrega',
            'Instalação-Reparo não concluídos',
            'Não recebi',
            'Produto errado',
            'Montagem',
            'Produto não recebido',
            'Produtos divergentes',
            'Projeto divergente'
        },
        'Online Services': {
            'Aplicativos',
            'Canais de Atendimento',
            'Marketplace',
            'Problemas com o Site',
            'Problemas para utilizar aplicativos',
            'Site fora do ar-Lento',
            'Sites e portais'
        }
    }
}

relative_date = {
    'uma semana atrás': 7,
    '2 semanas atrás': 14,
    '3 semanas atrás': 21,
    '4 semanas atrás': 28,
    '4 weeks ago': 28,
    'um mês atrás': 30,
    'a month ago': 30,
    '2 meses atrás': 60,
    '2 months ago': 60,
    '3 meses atrás': 90,
    '3 months ago': 90,
    '4 meses atrás': 120,
    '4 months ago': 120,
    '5 meses atrás': 150,
    '5 months ago': 150,
    '6 meses atrás': 180,
    '6 months ago': 180,
    '7 meses atrás': 210,
    '7 months ago': 210,
    '8 meses atrás': 240,
    '8 months ago': 240,
    '9 meses atrás': 270,
    '9 months ago': 270,
    '10 meses atrás': 300,
    '10 months ago': 300,
    '11 meses atrás': 330,
    '11 months ago': 330,
    'um ano atrás': 365,
    'a year ago': 365,
    '2 anos atrás': 730,
    '2 years ago': 730,
    '3 anos atrás': 1095,
    '3 years ago': 1095,
    '4 anos atrás': 1460,
    '4 years ago': 1460,
    '5 anos atrás': 1825,
    '5 years ago': 1460,
    '6 anos atrás': 2190,
    '6 years ago': 1460,
    '7 anos atrás': 2555,
    '7 years ago': 1460,
    '8 anos atrás': 2920,
    '8 years ago': 1460,
}
